<?php

declare(strict_types=1);

namespace App\Domain\PlotInventory\Models;

use App\Domain\CemeteryCapability\Models\CemeteryPackage;
use App\Domain\PlotInventory\PlotState;
use App\Domain\PlotReservation\Models\PlotReservation;
use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Support\Facades\DB;
use InvalidArgumentException;

/**
 * Eloquent model for `grave_plots` — the authoritative per-plot inventory
 * rows (`docs/superpowers/specs/2026-08-16-plot-inventory-reservation-
 * design.md` §4.1). Bulk-generated by
 * `App\Domain\PlotInventory\Actions\CreateCemeteryBlock` with slots
 * zero-padded `001..N` and `plot_state = available`; `plot_state` is the
 * authoritative per-plot availability the reservation module (P3 lane 2,
 * `plot_reservations`) flips.
 *
 * `id` is a UUID (`HasUuids`), the same contract-wide shape
 * `docs/contracts/openapi.yaml` fixes for `PlotId`.
 *
 * ---------------------------------------------------------------------------
 * Guards (booted)
 * ---------------------------------------------------------------------------
 * - saving: `plot_state` must be one of `PlotState::KNOWN_STATES`.
 * - deleting: refused — as `InvalidArgumentException` with an honest
 *   message — while the plot is not `available`, or while ANY
 *   `plot_reservations` history row exists for it (`plot_reservations`
 *   is append-only, so any row — held, confirmed, released, or expired —
 *   is history that a delete would lose). The state check runs first:
 *   it is the cheap in-memory refusal and the common case; the
 *   reservations check needs the `plot_reservations` table, which lands
 *   with P3 lane 2.
 */
final class GravePlot extends Model
{
    use HasUuids;

    protected $table = 'grave_plots';

    /**
     * @var list<string>
     */
    protected $fillable = [
        'block_id',
        'slot',
        'plot_state',
        'cemetery_package_id',
    ];

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'plot_state' => 'string',
            'cemetery_package_id' => 'integer',
        ];
    }

    protected static function booted(): void
    {
        self::saving(function (self $plot): void {
            PlotState::assertKnown((string) $plot->plot_state);
        });

        self::deleting(function (self $plot): void {
            if ($plot->plot_state !== PlotState::AVAILABLE) {
                throw new InvalidArgumentException(
                    "Cannot delete grave plot [{$plot->slot}] in block [{$plot->block_id}]: only plots in the ".
                    "'available' state may be deleted, this plot is '{$plot->plot_state}'."
                );
            }

            if (DB::table('plot_reservations')->where('plot_id', $plot->getKey())->exists()) {
                throw new InvalidArgumentException(
                    "Cannot delete grave plot [{$plot->slot}] in block [{$plot->block_id}]: ".
                    'plot_reservations history exists for it.'
                );
            }
        });
    }

    /**
     * @return BelongsTo<CemeteryBlock, $this>
     */
    public function block(): BelongsTo
    {
        return $this->belongsTo(CemeteryBlock::class, 'block_id');
    }

    /**
     * @return BelongsTo<CemeteryPackage, $this>
     */
    public function cemeteryPackage(): BelongsTo
    {
        return $this->belongsTo(CemeteryPackage::class, 'cemetery_package_id');
    }

    /**
     * Reservation history for this plot (`plot_reservations`, append-only)
     * — the P3 lane 2 module owns the table and model; this relation is the
     * Task 2 landing spot the Task 1 review flagged, added early so the
     * merge with lane 2 (which ships `PlotReservation`) resolves it.
     */
    public function reservations(): HasMany
    {
        return $this->hasMany(PlotReservation::class, 'plot_id');
    }
}
