<?php

declare(strict_types=1);

namespace App\Filament\Admin\Resources\GravePlots\Schemas;

use App\Domain\PlotInventory\PlotState;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\TextInput;
use Filament\Schemas\Schema;

/**
 * Resource-contract form for `GravePlotsResource`.
 *
 * The current scope is list-only (no create/edit pages exist — plots are
 * bulk-generated by `CreateCemeteryBlock` and their state is changed by the
 * table's override actions), so no page renders this schema today. It is
 * declared so the resource has a defined shape if a create/edit page is
 * ever added deliberately, and its fields mirror the model's fillable
 * exactly. `block_id` and `slot` are read-only when shown: neither may be
 * re-targeted once a plot exists (the `(block_id, slot)` pair is
 * authoritative and `block_id` is `restrictOnDelete`).
 */
final class GravePlotForm
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->columns(2)
            ->components([
                Select::make('block_id')
                    ->label('Blok')
                    ->relationship('block', 'code')
                    ->required()
                    ->disabled(),

                TextInput::make('slot')
                    ->label('Slot')
                    ->required()
                    ->disabled(),

                Select::make('plot_state')
                    ->label('Status')
                    ->required()
                    ->native(false)
                    ->options(array_combine(
                        PlotState::KNOWN_STATES,
                        ['Tersedia', 'Dipesan', 'Terisi', 'Perawatan'],
                    )),

                Select::make('cemetery_package_id')
                    ->label('Paket / Kelas')
                    ->relationship('cemeteryPackage', 'name')
                    ->nullable(),
            ]);
    }
}
