<?php

declare(strict_types=1);

namespace Database\Factories;

use App\Domain\CemeteryDirectory\Models\Cemetery;
use App\Domain\GraveRegistry\GraveRecordAccessMode;
use App\Domain\GraveRegistry\GraveRecordSource;
use App\Domain\GraveRegistry\Models\GraveRecord;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * Test-fixture factory for `grave_records`, following `UserFactory` — the
 * only factory that existed in this repository before this one. Added for
 * `tests/Feature/Domain/Renewal/RenewalSchemaTest.php`, which needs a real
 * `grave_records` row (specifically its `due_date`) to exercise the AC11
 * duplicate-period guard; nothing about that guard is specific to
 * `GraveRegistry`, so this factory is deliberately minimal rather than
 * exercising every column that domain's own tests already cover directly
 * with `GraveRecord::create([...])`.
 *
 * `cemetery_id` is not generated by a `Cemetery` factory — none exists, and
 * `2026_07_26_190300_seed_cemeteries_and_capability_profiles.php` already
 * seeds ten fixture cemeteries as part of every migration run (including
 * under `RefreshDatabase`), so this factory picks the first one rather than
 * inventing a second cemetery-creation path.
 *
 * @extends Factory<GraveRecord>
 */
final class GraveRecordFactory extends Factory
{
    protected $model = GraveRecord::class;

    /**
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'cemetery_id' => fn () => Cemetery::query()->firstOrFail()->id,
            'deceased_name' => fake()->name(),
            'block' => 'A-'.fake()->numberBetween(1, 99),
            'death_date' => fake()->dateTimeBetween('-5 years', '-1 years')->format('Y-m-d'),
            'due_date' => fake()->dateTimeBetween('now', '+3 years')->format('Y-m-d'),
            'access_mode' => GraveRecordAccessMode::OPEN,
            'source' => GraveRecordSource::CONTOH,
            'source_updated_at' => now(),
        ];
    }
}
