<?php

declare(strict_types=1);

namespace Database\Factories;

use App\Domain\GraveRegistry\Models\GraveRecord;
use App\Domain\Renewal\Models\Renewal;
use App\Domain\Renewal\RenewalSource;
use App\Domain\Renewal\RenewalStatus;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * Test-fixture factory for `renewals`, following `GraveRecordFactory` — the
 * precedent for a domain model namespaced under `App\Domain\...\Models`.
 * Added as the ride-along half of fix round 1: later tasks in
 * `docs/superpowers/plans/2026-08-12-platform-renewal-completion.md` (5, 6,
 * 7) call `Renewal::factory()->create(...)` in their own pre-written test
 * code, so `Renewal` shipped `HasFactory` in that same commit and this
 * factory is the other half of that pairing.
 *
 * `grave_record_id` is generated by `GraveRecord::factory()` — the sibling
 * factory this repository already has for that table — rather than the
 * "pick the first seeded cemetery" trick `GraveRecordFactory` itself uses,
 * because a renewal only has meaning against a real `grave_records` row and
 * this factory has no reason to short-circuit that.
 *
 * @extends Factory<Renewal>
 */
final class RenewalFactory extends Factory
{
    protected $model = Renewal::class;

    /**
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'grave_record_id' => fn () => GraveRecord::factory()->create()->id,
            'target_due_period' => now()->addYear()->format('Y-m-d'),
            'reference' => 'PPJ-'.fake()->unique()->numberBetween(1_000, 99_999),
            'status' => RenewalStatus::MENUNGGU_PEMBAYARAN,
            'source' => RenewalSource::ONLINE,
            'settled_at' => null,
        ];
    }
}
