<?php

declare(strict_types=1);

namespace App\Platform\IdentityAccess\Mfa\Totp;

/**
 * RFC 4648 §6 Base32 encode/decode — no external dependency, matching this
 * batch's brief ("Implement TOTP yourself in pure PHP"). Used ONLY for
 * secret storage/display: a TOTP secret is conventionally shown to a human
 * (manual entry) or embedded in an `otpauth://` URI (for a future QR
 * renderer) as Base32, per RFC 6238's own convention.
 *
 * Verified against RFC 4648 §10's own test vectors in
 * `tests/Unit/Platform/IdentityAccess/Mfa/Totp/Base32Test.php` — "" -> "",
 * "f" -> "MY======", "fo" -> "MZXQ====", "foo" -> "MZXW6===",
 * "foob" -> "MZXW6YQ=", "fooba" -> "MZXW6YTB",
 * "foobar" -> "MZXW6YTBOI======".
 *
 * Deliberately NOT used for anything cryptographic on its own — it is an
 * encoding, not an encryption or hashing scheme. The TOTP secret itself is
 * generated by `TotpSecret::generate()` (`random_bytes`) and persisted via
 * Laravel's `encrypted` Eloquent cast (`Mfa\Models\MfaEnrolment::casts()`),
 * never stored as plain Base32 text outside that encrypted column.
 */
final class Base32
{
    private const string ALPHABET = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';

    /**
     * Encode raw bytes to a padded, uppercase Base32 string.
     */
    public static function encode(string $data): string
    {
        if ($data === '') {
            return '';
        }

        $bits = '';
        foreach (str_split($data) as $byte) {
            $bits .= str_pad(decbin(ord($byte)), 8, '0', STR_PAD_LEFT);
        }

        $output = '';
        foreach (str_split($bits, 5) as $chunk) {
            $chunk = str_pad($chunk, 5, '0', STR_PAD_RIGHT);
            $output .= self::ALPHABET[bindec($chunk)];
        }

        $padLength = (8 - (strlen($output) % 8)) % 8;

        return $output.str_repeat('=', $padLength);
    }

    /**
     * Decode a Base32 string back to raw bytes. Tolerant of missing
     * padding, lowercase input, and surrounding whitespace (all common in
     * hand-typed/manual-entry secrets) — anything outside the Base32
     * alphabet is stripped rather than rejected, since the only caller of
     * this method today is this module's own round-trip of a
     * self-generated secret, never untrusted external input.
     */
    public static function decode(string $base32): string
    {
        $normalized = strtoupper(preg_replace('/[^A-Za-z2-7]/', '', $base32) ?? '');

        if ($normalized === '') {
            return '';
        }

        $bits = '';
        foreach (str_split($normalized) as $char) {
            $position = strpos(self::ALPHABET, $char);

            if ($position === false) {
                continue;
            }

            $bits .= str_pad(decbin($position), 5, '0', STR_PAD_LEFT);
        }

        $output = '';
        foreach (str_split($bits, 8) as $byteBits) {
            // A trailing group shorter than 8 bits is padding introduced by
            // the 5-bit-to-8-bit regrouping, never a real data byte —
            // discard it rather than reading garbage.
            if (strlen($byteBits) < 8) {
                break;
            }

            $output .= chr(bindec($byteBits));
        }

        return $output;
    }
}
