<?php

declare(strict_types=1);

namespace Tests\Feature\Filament;

use App\Domain\CemeteryCapability\CemeteryPackageAvailabilityStatus;
use App\Domain\CemeteryCapability\Models\CemeteryPackage;
use App\Domain\CemeteryDirectory\Access\CurrentCemeteryScope;
use App\Domain\CemeteryDirectory\Models\Cemetery;
use App\Domain\CemeteryDirectory\PlotTrackingMode;
use App\Domain\PlotInventory\Actions\CreateCemeteryBlock;
use App\Domain\PlotInventory\Models\CemeteryBlock;
use App\Filament\Admin\Pages\PlotFloorMap as AdminPlotFloorMap;
use App\Filament\Operator\Pages\PlotFloorMap as OperatorPlotFloorMap;
use App\Models\User;
use App\Platform\IdentityAccess\Roles\ActorRole;
use App\Platform\IdentityAccess\Scopes\Models\ScopeAssignment;
use App\Platform\IdentityAccess\Scopes\ScopeEntityType;
use Filament\Facades\Filament;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\DB;
use Livewire\Livewire;
use Tests\Support\GrantsActorRoles;
use Tests\TestCase;

/**
 * The Phase D plot availability dashboard — rendering, cemetery-options
 * scoping, and the `plot_tracking_mode` branch.
 *
 * Every fixture is a real row against real Postgres: blocks and their
 * plots are generated by the shipped `CreateCemeteryBlock` action rather
 * than hand-inserted, so the test exercises the same slot numbering and
 * default `available` state the live admin surfaces produce.
 */
final class PlotFloorMapPageTest extends TestCase
{
    use GrantsActorRoles;
    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp();
        $this->withoutVite();
    }

    private function admin(): User
    {
        $user = User::factory()->create();
        $this->grantRoleTo($user, ActorRole::ADMIN);
        $this->actingAs($user);

        return $user;
    }

    private function granularCemeteryWithBlock(User $actor, int $capacity = 3): Cemetery
    {
        $cemetery = Cemetery::factory()->create([
            'plot_tracking_mode' => PlotTrackingMode::GRANULAR,
        ]);

        app(CreateCemeteryBlock::class)($cemetery, 'BLOK-A', 'Blok A', $capacity, $actor->id, 'admin');

        return $cemetery;
    }

    private function aggregateCemeteryWithPackage(): Cemetery
    {
        $cemetery = Cemetery::factory()->create([
            'plot_tracking_mode' => PlotTrackingMode::AGGREGATE,
        ]);

        CemeteryPackage::query()->create([
            'cemetery_id' => $cemetery->getKey(),
            'name' => 'Paket Utama',
            'availability_status' => CemeteryPackageAvailabilityStatus::LIMITED,
            'sort_order' => 1,
            'is_active' => true,
        ]);

        return $cemetery;
    }

    // -----------------------------------------------------------------
    // Access
    // -----------------------------------------------------------------

    public function test_back_office_roles_can_access_the_admin_page(): void
    {
        foreach ([ActorRole::ADMIN, ActorRole::RESTRICTED_ADMIN, ActorRole::OPERATOR, ActorRole::FINANCE] as $role) {
            $user = User::factory()->create();
            $this->grantRoleTo($user, $role);
            $this->actingAs($user);

            $this->assertTrue(AdminPlotFloorMap::canAccess(), "role {$role}");
            $this->forgetResolvedActorContext();
        }
    }

    public function test_a_vendor_cannot_access_the_admin_page(): void
    {
        $user = User::factory()->create();
        $this->grantRoleTo($user, ActorRole::VENDOR);
        $this->actingAs($user);

        $this->assertFalse(AdminPlotFloorMap::canAccess());

        Livewire::actingAs($user)->test(AdminPlotFloorMap::class)->assertForbidden();
    }

    // -----------------------------------------------------------------
    // Cemetery options — /admin sees everything
    // -----------------------------------------------------------------

    public function test_the_admin_page_offers_every_cemetery(): void
    {
        $actor = $this->admin();
        $granular = $this->granularCemeteryWithBlock($actor);
        $aggregate = $this->aggregateCemeteryWithPackage();

        $options = (new AdminPlotFloorMap)->cemeteryOptions();

        $this->assertArrayHasKey((string) $granular->getKey(), $options);
        $this->assertArrayHasKey((string) $aggregate->getKey(), $options);
    }

    // -----------------------------------------------------------------
    // The plot_tracking_mode branch — the phase's core requirement
    // -----------------------------------------------------------------

    public function test_a_granular_cemetery_renders_the_floor_block_map(): void
    {
        $actor = $this->admin();
        $cemetery = $this->granularCemeteryWithBlock($actor);

        Livewire::actingAs($actor)
            ->test(AdminPlotFloorMap::class)
            ->set('cemeteryId', (string) $cemetery->getKey())
            ->assertSee('BLOK-A')
            ->assertSee('001')
            ->assertSee('Tersedia')
            ->assertDontSee('Kuota per paket');
    }

    public function test_an_aggregate_cemetery_renders_quota_cards_from_the_same_page(): void
    {
        $actor = $this->admin();
        $cemetery = $this->aggregateCemeteryWithPackage();

        Livewire::actingAs($actor)
            ->test(AdminPlotFloorMap::class)
            ->set('cemeteryId', (string) $cemetery->getKey())
            ->assertSee('Kuota per paket')
            ->assertSee('Paket Utama')
            ->assertSee('Terbatas')
            ->assertDontSee('BLOK-A');
    }

    public function test_switching_the_selected_cemetery_switches_the_rendered_view(): void
    {
        $actor = $this->admin();
        $granular = $this->granularCemeteryWithBlock($actor);
        $aggregate = $this->aggregateCemeteryWithPackage();

        Livewire::actingAs($actor)
            ->test(AdminPlotFloorMap::class)
            ->set('cemeteryId', (string) $granular->getKey())
            ->assertSee('BLOK-A')
            ->set('cemeteryId', (string) $aggregate->getKey())
            ->assertSee('Kuota per paket')
            ->assertDontSee('BLOK-A');
    }

    public function test_no_selection_renders_the_prompt_and_no_map(): void
    {
        $actor = $this->admin();
        $this->granularCemeteryWithBlock($actor);
        $this->aggregateCemeteryWithPackage();

        Livewire::actingAs($actor)
            ->test(AdminPlotFloorMap::class)
            ->assertSee('Pilih makam untuk melihat ketersediaan plot.')
            ->assertDontSee('BLOK-A');
    }

    public function test_a_single_available_cemetery_is_preselected_on_mount(): void
    {
        $actor = $this->admin();
        $cemetery = $this->granularCemeteryWithBlock($actor);

        // `2026_07_26_190300_seed_cemeteries_and_capability_profiles.php` runs
        // on every `RefreshDatabase` migration, so the directory is never
        // actually empty. `/admin`'s cemeteryOptions() is unconditionally
        // "every cemetery", so exercising the true "exactly one option"
        // branch here requires clearing the other seeded cemeteries first —
        // `grave_records` RESTRICTs the FK, so its rows for those cemeteries
        // must go first (mirrors the migration's own down() reasoning).
        $otherCemeteryIds = Cemetery::query()->where('id', '!=', $cemetery->getKey())->pluck('id');
        DB::table('grave_records')->whereIn('cemetery_id', $otherCemeteryIds)->delete();
        Cemetery::query()->whereIn('id', $otherCemeteryIds)->delete();

        Livewire::actingAs($actor)
            ->test(AdminPlotFloorMap::class)
            ->assertSet('cemeteryId', (string) $cemetery->getKey())
            ->assertSee('BLOK-A');
    }

    public function test_a_granular_cemetery_with_no_blocks_renders_an_honest_empty_state(): void
    {
        $this->admin();
        $cemetery = Cemetery::factory()->create(['plot_tracking_mode' => PlotTrackingMode::GRANULAR]);

        Livewire::test(AdminPlotFloorMap::class)
            ->set('cemeteryId', (string) $cemetery->getKey())
            ->assertSee('belum memiliki blok');
    }

    // -----------------------------------------------------------------
    // Untrusted-input safety (correction 7: uuid columns on real Postgres)
    // -----------------------------------------------------------------

    public function test_a_malformed_cemetery_id_renders_the_prompt_instead_of_erroring(): void
    {
        $actor = $this->admin();
        $this->granularCemeteryWithBlock($actor);

        Livewire::actingAs($actor)
            ->test(AdminPlotFloorMap::class)
            ->set('cemeteryId', 'not-a-uuid')
            ->assertOk()
            ->assertSee('Pilih makam untuk melihat ketersediaan plot.');
    }

    public function test_a_malformed_plot_id_on_open_plot_resolves_to_nothing_instead_of_erroring(): void
    {
        $actor = $this->admin();
        $cemetery = $this->granularCemeteryWithBlock($actor);

        Livewire::actingAs($actor)
            ->test(AdminPlotFloorMap::class)
            ->set('cemeteryId', (string) $cemetery->getKey())
            ->call('openPlot', 'not-a-uuid')
            ->assertSet('activePlotId', null)
            ->assertOk();
    }

    public function test_a_plot_from_another_cemetery_is_not_addressable(): void
    {
        $actor = $this->admin();
        $own = $this->granularCemeteryWithBlock($actor);
        $other = $this->granularCemeteryWithBlock($actor);

        $foreignPlot = CemeteryBlock::query()
            ->where('cemetery_id', $other->getKey())
            ->firstOrFail()
            ->plots()
            ->firstOrFail();

        Livewire::actingAs($actor)
            ->test(AdminPlotFloorMap::class)
            ->set('cemeteryId', (string) $own->getKey())
            ->call('openPlot', (string) $foreignPlot->getKey())
            ->assertSet('activePlotId', null);
    }

    public function test_the_page_is_registered_on_the_admin_panel(): void
    {
        $this->assertContains(
            AdminPlotFloorMap::class,
            Filament::getPanel('admin')->getPages(),
        );
    }

    /**
     * A real cemetery-operator: the `cemetery_operator` role grant that
     * lets them through `CemeteryOperatorPanelAccessPolicy`, plus a real
     * `scope_assignments` row per granted cemetery. No fabricated
     * ActorContext — the whole chain is exercised.
     *
     * @param  list<string>  $cemeteryIds
     */
    private function actingAsCemeteryOperator(array $cemeteryIds): User
    {
        $user = User::factory()->create();
        $this->grantRoleTo($user, ActorRole::CEMETERY_OPERATOR);

        foreach ($cemeteryIds as $cemeteryId) {
            ScopeAssignment::query()->create([
                'actor_identifier' => (string) $user->id,
                'entity_type' => ScopeEntityType::CEMETERY,
                'entity_id' => $cemeteryId,
            ]);
        }

        $this->actingAs($user);
        $this->forgetResolvedActorContext();
        $this->app->forgetScopedInstances();

        return $user;
    }

    // -----------------------------------------------------------------
    // The verification bar: /admin sees all, /operator sees only granted
    // -----------------------------------------------------------------

    public function test_an_operator_sees_only_the_cemetery_they_are_granted(): void
    {
        $setupActor = $this->admin();
        $own = $this->granularCemeteryWithBlock($setupActor);
        $other = $this->granularCemeteryWithBlock($setupActor);

        $this->actingAsCemeteryOperator([(string) $own->getKey()]);

        $options = (new OperatorPlotFloorMap)->cemeteryOptions();

        $this->assertArrayHasKey((string) $own->getKey(), $options);
        $this->assertArrayNotHasKey((string) $other->getKey(), $options);
    }

    public function test_the_admin_page_sees_both_cemeteries_the_operator_page_narrows(): void
    {
        $setupActor = $this->admin();
        $own = $this->granularCemeteryWithBlock($setupActor);
        $other = $this->granularCemeteryWithBlock($setupActor);

        $adminOptions = (new AdminPlotFloorMap)->cemeteryOptions();
        $this->assertArrayHasKey((string) $own->getKey(), $adminOptions);
        $this->assertArrayHasKey((string) $other->getKey(), $adminOptions);

        $this->actingAsCemeteryOperator([(string) $own->getKey()]);
        $this->assertCount(1, (new OperatorPlotFloorMap)->cemeteryOptions());
    }

    /**
     * The property is client-writable; the select's option list is a
     * render fact, not a security property. Setting `cemeteryId` over the
     * wire to a cemetery the operator holds no grant for must resolve to
     * nothing — not to that cemetery's inventory.
     */
    public function test_an_operator_cannot_wire_their_way_into_an_ungranted_cemetery(): void
    {
        $setupActor = $this->admin();
        $own = $this->granularCemeteryWithBlock($setupActor);
        $other = Cemetery::factory()->create(['plot_tracking_mode' => PlotTrackingMode::GRANULAR]);
        app(CreateCemeteryBlock::class)($other, 'BLOK-Z', 'Blok Z', 2, $setupActor->id, 'admin');

        $operator = $this->actingAsCemeteryOperator([(string) $own->getKey()]);

        Livewire::actingAs($operator)
            ->test(OperatorPlotFloorMap::class)
            ->set('cemeteryId', (string) $other->getKey())
            ->assertOk()
            ->assertSee('Pilih makam untuk melihat ketersediaan plot.')
            ->assertDontSee('BLOK-Z');
    }

    public function test_an_operator_with_no_grant_cannot_access_the_operator_page(): void
    {
        $user = User::factory()->create();
        $this->grantRoleTo($user, ActorRole::CEMETERY_OPERATOR);
        $this->actingAs($user);
        $this->app->forgetScopedInstances();

        $this->assertFalse(app(CurrentCemeteryScope::class)->hasAnyGrant());
        $this->assertFalse(OperatorPlotFloorMap::canAccess());
    }

    public function test_a_guest_cannot_access_the_operator_page(): void
    {
        $this->assertFalse(OperatorPlotFloorMap::canAccess());
    }

    public function test_the_operator_page_renders_the_granted_cemeterys_map(): void
    {
        $setupActor = $this->admin();
        $own = $this->granularCemeteryWithBlock($setupActor);

        $operator = $this->actingAsCemeteryOperator([(string) $own->getKey()]);

        Livewire::actingAs($operator)
            ->test(OperatorPlotFloorMap::class)
            ->assertSet('cemeteryId', (string) $own->getKey())
            ->assertSee('BLOK-A')
            ->assertSee('001');
    }

    public function test_the_operator_page_renders_quota_cards_for_an_aggregate_cemetery(): void
    {
        $aggregate = $this->aggregateCemeteryWithPackage();

        $operator = $this->actingAsCemeteryOperator([(string) $aggregate->getKey()]);

        Livewire::actingAs($operator)
            ->test(OperatorPlotFloorMap::class)
            ->assertSee('Kuota per paket')
            ->assertSee('Paket Utama')
            ->assertSee('Terbatas');
    }

    /**
     * The roadmap's stated invariant: the two subclasses differ in
     * cemetery-options scoping and nothing else. A second overridden
     * method is a second place scoping could drift, so the shape itself is
     * asserted, not just its current behaviour.
     */
    public function test_the_two_subclasses_override_only_the_options_source_and_access_gate(): void
    {
        $allowed = ['cemeteryOptions', 'canAccess'];

        foreach ([AdminPlotFloorMap::class, OperatorPlotFloorMap::class] as $subclass) {
            $declared = array_map(
                static fn (\ReflectionMethod $method): string => $method->getName(),
                (new \ReflectionClass($subclass))->getMethods(),
            );

            $ownMethods = array_values(array_filter(
                $declared,
                static fn (string $name): bool => (new \ReflectionMethod($subclass, $name))
                    ->getDeclaringClass()->getName() === $subclass,
            ));

            sort($ownMethods);
            $expected = $allowed;
            sort($expected);

            $this->assertSame($expected, $ownMethods, "{$subclass} declares an unexpected method.");
        }
    }

    public function test_the_page_is_registered_on_the_operator_panel(): void
    {
        $this->assertContains(
            OperatorPlotFloorMap::class,
            Filament::getPanel('operator')->getPages(),
        );
    }
}
