<?php

declare(strict_types=1);

namespace App\Filament\Admin\Resources\GravePlots;

use App\Domain\PlotInventory\Models\GravePlot;
use App\Filament\Admin\Resources\GravePlots\Pages\ListGravePlots;
use App\Filament\Admin\Resources\GravePlots\Schemas\GravePlotForm;
use App\Filament\Admin\Resources\GravePlots\Tables\GravePlotsTable;
use App\Platform\IdentityAccess\ActorContext;
use App\Platform\IdentityAccess\MasterData\Contracts\MasterDataAdminAuthorizerContract;
use App\Platform\IdentityAccess\MasterData\Exceptions\MasterDataNotAuthorisedException;
use App\Platform\IdentityAccess\Roles\ActorRole;
use BackedEnum;
use Filament\Resources\Resource;
use Filament\Schemas\Schema;
use Filament\Support\Icons\Heroicon;
use Filament\Tables\Table;
use Illuminate\Auth\Access\Response;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use UnitEnum;

/**
 * Admin management surface for `grave_plots` — the per-plot inventory rows
 * (`docs/superpowers/specs/2026-08-16-plot-inventory-reservation-design.md`
 * §4.1), read-only plus the three audited state-override row actions
 * ('Tandai Terisi' / 'Tandai Perawatan' / 'Tandai Tersedia'). There is
 * deliberately NO create/edit/delete page and NO delete action: plots are
 * bulk-generated by `CreateCemeteryBlock` (the block relation manager), and
 * deletion is guarded on the model (only `available` plots without
 * `plot_reservations` history) — no delete surface is offered until a
 * business need for one exists.
 *
 * Since 28 Aug 2026 this is no longer the only plot surface: Phase D's
 * `App\Filament\Admin\Pages\PlotFloorMap` renders the same inventory as a
 * block-grouped map for granular-tier cemeteries and offers the same three
 * state overrides through the shared
 * `App\Filament\Shared\PlotInventory\PlotStateOverrides`. This resource is
 * unchanged and deliberately kept: it is the only surface that lists plots
 * across ALL cemeteries at once, with search and filters, which the
 * per-cemetery map does not do.
 *
 * Same access gate shape as `CemeteryResource` and the sibling order
 * resources: one `canAccess()` + one `getAuthorizationResponse()` both
 * delegating to the shared `MasterDataAdminAuthorizerContract` four-role
 * gate, and one `auditRoleFor()` walking that gate's fixed role precedence
 * for the `Audit::record()` calls the state-override actions make.
 */
final class GravePlotsResource extends Resource
{
    protected static ?string $model = GravePlot::class;

    protected static ?string $slug = 'petak-makam';

    protected static string|BackedEnum|null $navigationIcon = Heroicon::OutlinedSquares2x2;

    protected static ?string $recordTitleAttribute = 'slot';

    public static function canAccess(): bool
    {
        try {
            app(MasterDataAdminAuthorizerContract::class)->authorize(app(ActorContext::class));
        } catch (MasterDataNotAuthorisedException) {
            return false;
        }

        return true;
    }

    public static function getAuthorizationResponse(string|UnitEnum $action, ?Model $record = null): Response
    {
        try {
            app(MasterDataAdminAuthorizerContract::class)->authorize(app(ActorContext::class));
        } catch (MasterDataNotAuthorisedException) {
            return Response::deny('Anda tidak berwenang mengelola plot makam.');
        }

        return Response::allow();
    }

    public static function form(Schema $schema): Schema
    {
        return GravePlotForm::configure($schema);
    }

    public static function table(Table $table): Table
    {
        return GravePlotsTable::configure($table);
    }

    public static function getEloquentQuery(): Builder
    {
        return GravePlot::query()->with(['block.cemetery', 'cemeteryPackage']);
    }

    public static function getPages(): array
    {
        return [
            'index' => ListGravePlots::route('/'),
        ];
    }

    public static function getModelLabel(): string
    {
        return 'plot makam';
    }

    public static function getPluralModelLabel(): string
    {
        return 'Plot Makam';
    }

    public static function getNavigationLabel(): string
    {
        return 'Plot Makam';
    }

    /**
     * The single deterministic `actor_role` value for this resource's
     * `Audit::record()` calls — same reasoning and shape as
     * `CemeteryResource::auditRoleFor()` (the shared master-data gate has no
     * per-role distinction, so one deterministic value is derived by walking
     * the authorizer's fixed four-role precedence order).
     */
    public static function auditRoleFor(ActorContext $actor): string
    {
        if (! $actor->isAuthenticated()) {
            return 'guest';
        }

        foreach ([
            ActorRole::ADMIN,
            ActorRole::RESTRICTED_ADMIN,
            ActorRole::OPERATOR,
            ActorRole::FINANCE,
        ] as $role) {
            if ($actor->hasRole($role)) {
                return $role;
            }
        }

        return 'authenticated_actor';
    }
}
