<?php

declare(strict_types=1);

use App\Support\ExampleData\VendorListingExampleData;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

/**
 * ===========================================================================
 * THIS IS DUMMY / PLACEHOLDER DATA. NONE OF THE FOLLOWING IS REAL.
 * ===========================================================================
 * Every row below is a FICTIONAL marketplace vendor and offer, generated by
 * `App\Support\ExampleData\VendorListingExampleData`:
 *
 *   - no "Toko Bunga Contoh N" vendor exists; the literal "Contoh"
 *     (Indonesian for "Example") marker is on every name, the same
 *     fabricated-data convention as "Jl. Contoh ..." in the cemetery seed
 *     and the dummy grave-record names;
 *   - no listing price is a claim about any real seller's price — prices
 *     are the catalogue's own example base price in minor units;
 *   - cancellation policies are marked "Contoh kebijakan pembatalan";
 *   - availability/evidence values cycle the closed lists purely by index.
 *
 * The nine `products` rows stay the canonical catalogue master data
 * (`2026_07_26_180200_seed_marketplace_products_and_variants.php`); this
 * migration only adds the per-vendor OFFERS that table always anticipated
 * but that `2026_08_12_100020_create_vendor_listings_table.php` could not
 * ship with (its parent `vendors` table was empty). A later batch working
 * from real vendor agreements replaces these rows wholesale.
 *
 * ---------------------------------------------------------------------------
 * Why this exists at all — the missing bootstrap
 * ---------------------------------------------------------------------------
 * `vendors` and `vendor_listings` are create-only migrations with ZERO rows
 * in every fresh environment, so the marketplace browse → add → cart →
 * checkout journey dies at the first "add to cart" button: no offer exists
 * to add (`ProductDetail::firstActiveListing()` returns `null` and the page
 * honestly renders "Pemesanan online belum tersedia"). Seeding one active
 * listing per product (one per `ProductCode`, the catalogue's own closed
 * list) makes the marketplace operable end to end in dev, staging, and CI
 * while keeping the catalogue untouched.
 *
 * ---------------------------------------------------------------------------
 * Why a data migration and not `database/seeders/`
 * ---------------------------------------------------------------------------
 * Nothing in CI, the Dockerfile, or any deployment script runs
 * `php artisan db:seed`, so a seeder class would never execute. Every
 * catalogue and master-data set in this repository ships as a timestamped
 * data migration (same reasoning as `2026_07_26_170400_seed_faq_
 * categories_and_articles.php` and `2026_08_08_100010_seed_example_grave_
 * records.php`).
 *
 * Migration timestamp slot: `2026_08_14_100000`, after the L11 marketplace
 * checkout lane's schema migrations (`2026_08_12_*`).
 *
 * ---------------------------------------------------------------------------
 * `down()` deletes exactly what `up()` inserted
 * ---------------------------------------------------------------------------
 * Listings are deleted first (their FK to `vendors` is restrict-on-delete),
 * scoped to the synthetic vendor ids; vendors are then deleted by the
 * generated names. Never a blanket truncate (`makam-migration`;
 * AGENTS.md §Database) — a later real-data batch's rows can never be caught
 * by this rollback even if one of them somehow shared a name.
 */
return new class extends Migration
{
    public function up(): void
    {
        // The five vendors and nine listings are defined in
        // App\Support\ExampleData\VendorListingExampleData. It skips
        // (never fails on) a product code the catalogue seed did not
        // produce, exactly like `CemeteryExampleData::seedGraveRecords()`.
        VendorListingExampleData::seed();
    }

    public function down(): void
    {
        $names = array_column(VendorListingExampleData::vendors(), 0);

        $vendorIds = DB::table('vendors')->whereIn('name', $names)->pluck('id');

        DB::table('vendor_listings')->whereIn('vendor_id', $vendorIds)->delete();
        DB::table('vendors')->whereIn('name', $names)->delete();
    }
};
