<?php

declare(strict_types=1);

use App\Domain\PlotInventory\PlotState;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * `grave_plots` — the authoritative per-plot inventory rows
 * (`docs/superpowers/specs/2026-08-16-plot-inventory-reservation-design.md`
 * §4.1). One row per physical grave plot, bulk-generated by
 * `App\Domain\PlotInventory\Actions\CreateCemeteryBlock` with slots
 * zero-padded `001..N`; `plot_state` is the authoritative per-plot
 * availability the reservation module (P3 lane 2, `plot_reservations`)
 * flips through `reserved`/`occupied`/`maintenance`/`available`.
 *
 * ---------------------------------------------------------------------------
 * Column shape and the judgement calls behind it
 * ---------------------------------------------------------------------------
 * - `id` is a UUID — `docs/contracts/openapi.yaml` fixes `format: uuid`
 *   for `PlotId`; the same convention as `cemetery_blocks` (this row's
 *   parent) and `cemeteries`.
 *
 * - `block_id` is `restrictOnDelete`: deleting a block must not silently
 *   orphan (or take with it) authoritative plot state — whoever needs to
 *   delete a block with plots must deal with the plots explicitly first
 *   (each plot itself refuses deletion unless `available` and without
 *   `plot_reservations` history — see `GravePlot::booted()`).
 *
 * - `plot_state` is a plain string with application-layer validation
 *   (`PlotState::assertKnown` in `GravePlot::booted()`), the codebase's
 *   established convention for closed-list string columns — not a
 *   Postgres enum.
 *
 * - `cemetery_package_id` links a plot to its package/class row when the
 *   operator generated the block against one (`CemeteryPackage`, the
 *   `cemetery_packages` table), and is `nullOnDelete` — the class link is
 *   an indicative convenience reference, not the plot's identity; a
 *   package row being deleted must not take plots with it.
 *
 * - `slot` is unique per block (`001..N`), never globally.
 *
 * Migration timestamp slot: `2026_08_16_100010`, immediately after its
 * parent table `2026_08_16_100000_create_cemetery_blocks_table.php` (the
 * P3 plot-inventory plan's Task 1 brief assigns the slot range).
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('grave_plots', function (Blueprint $table) {
            $table->uuid('id')->primary();

            $table->foreignUuid('block_id')->constrained('cemetery_blocks')->restrictOnDelete();

            $table->string('slot');
            $table->string('plot_state', 16)->default(PlotState::AVAILABLE);

            $table->foreignId('cemetery_package_id')->nullable()->constrained('cemetery_packages')->nullOnDelete();

            $table->timestamps();

            $table->unique(['block_id', 'slot']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('grave_plots');
    }
};
