<?php

declare(strict_types=1);

namespace App\Domain\Visitation\Models;

use App\Domain\CemeteryDirectory\Models\Cemetery;
use Carbon\CarbonImmutable;
use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Str;
use InvalidArgumentException;

/**
 * Eloquent model for `visitation_bookings` — Task 1 of
 * `docs/superpowers/plans/2026-08-16-p4-memorial-qr-visitation.md`
 * (Lane 1 — Visitation). A requested visit; written by exactly one
 * Action (`App\Domain\Visitation\Actions\RequestVisitation`).
 *
 * ---------------------------------------------------------------------------
 * The model enforces data shape; the Action enforces the domain
 * ---------------------------------------------------------------------------
 * This model's guards are deliberately narrow — `visitor_count >= 1` and
 * a non-blank generated `reference` — because the load-bearing
 * guarantees of this table live in `RequestVisitation` and the schema:
 * capacity is enforced against the ledger row under `lockForUpdate()`
 * (never here), status transitions belong to the operator lane's later
 * actions, and `idempotency_key` uniqueness is the migration's
 * constraint (the Action's classifier translates a collision into an
 * incumbent return).
 *
 * `reference` — the confirmation-card handle — is generated by the
 * saving guard when absent: `VST-<year>-<8 uppercase alphanumerics>`
 * (the brief's exact shape). The suffix makes collisions astronomically
 * improbable; the idempotency key, not the reference, is the duplicate
 * safeguard.
 */
final class VisitationBooking extends Model
{
    use HasUuids;

    protected $table = 'visitation_bookings';

    /**
     * @var list<string>
     */
    protected $fillable = [
        'cemetery_id',
        'policy_id',
        'visit_date',
        'visitor_count',
        'contact_phone',
        'contact_email',
        'accessibility_needs',
        'facility_requests',
        'status',
        'idempotency_key',
        'reference',
    ];

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'visit_date' => 'immutable_date',
            'visitor_count' => 'integer',
            'facility_requests' => 'array',
        ];
    }

    protected static function booted(): void
    {
        self::saving(function (self $booking): void {
            if ((int) $booking->visitor_count < 1) {
                throw new InvalidArgumentException(
                    "Visitation booking visitor_count must be at least 1, got [{$booking->visitor_count}]."
                );
            }

            if (blank($booking->reference)) {
                $booking->reference = 'VST-'.CarbonImmutable::now()->format('Y').'-'.Str::upper(Str::random(8));
            }
        });
    }

    /**
     * The cemetery the visit is booked at — the admin bookings resource's
     * per-cemetery scoping and its `cemetery.name` column both read
     * through here.
     *
     * @return BelongsTo<Cemetery, $this>
     */
    public function cemetery(): BelongsTo
    {
        return $this->belongsTo(Cemetery::class, 'cemetery_id');
    }
}
